name: Deploy to GKE

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build & Push Docker image
        run: |
          docker build -t eu.gcr.io/review-ai-453511/my-node-app .
          docker push eu.gcr.io/review-ai-453511/my-node-app

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials my-cluster --region=europe-central2

      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
